<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="3" ignored="0" total="14" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="130" started-at="2020-02-20T15:53:42Z" finished-at="2020-02-20T15:53:43Z">
    <groups>
      <group name="performance">
        <method signature="GroupingTests.feature1()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature1" class="LearningTestNG.GroupingTests"/>
        <method signature="GroupingTests.feature3()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature3" class="LearningTestNG.GroupingTests"/>
      </group> <!-- performance -->
      <group name="regression">
        <method signature="GroupingTests.feature2()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature2" class="LearningTestNG.GroupingTests"/>
        <method signature="GroupingTests.feature3()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature3" class="LearningTestNG.GroupingTests"/>
      </group> <!-- regression -->
    </groups>
    <test name="Surefire test" duration-ms="130" started-at="2020-02-20T15:53:42Z" finished-at="2020-02-20T15:53:43Z">
      <class name="LearningTestNG.TestNGAnnotation_2">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="beforeSuite" is-config="true" duration-ms="22" started-at="2020-02-20T15:53:42Z" finished-at="2020-02-20T15:53:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-02-20T15:53:42Z" finished-at="2020-02-20T15:53:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="beforeClass" is-config="true" duration-ms="1" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test3()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="test3" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:LearningTestNG.TestNGAnnotation_2@79698539]" name="afterSuite" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- LearningTestNG.TestNGAnnotation_2 -->
      <class name="LearningTestNG.GroupingTests">
        <test-method status="PASS" signature="feature1()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature1" duration-ms="1" started-at="2020-02-20T15:53:42Z" finished-at="2020-02-20T15:53:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature1 -->
        <test-method status="PASS" signature="feature2()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature2" duration-ms="0" started-at="2020-02-20T15:53:42Z" finished-at="2020-02-20T15:53:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature2 -->
        <test-method status="PASS" signature="feature3()[pri:0, instance:LearningTestNG.GroupingTests@73f792cf]" name="feature3" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature3 -->
      </class> <!-- LearningTestNG.GroupingTests -->
      <class name="LearningTestNG.TestNGAnnotation">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test1()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="test1" duration-ms="1" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="test2()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="test2" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:LearningTestNG.TestNGAnnotation@dfd3711]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- LearningTestNG.TestNGAnnotation -->
      <class name="LearningTestNG.Listeners.LoginTest">
        <test-method status="PASS" signature="loginWithEmail()[pri:0, instance:LearningTestNG.Listeners.LoginTest@2ed94a8b]" name="loginWithEmail" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithEmail -->
        <test-method status="FAIL" signature="loginWithFacebook()[pri:0, instance:LearningTestNG.Listeners.LoginTest@2ed94a8b]" name="loginWithFacebook" duration-ms="3" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [TestString1] but found [TestString]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [TestString1] but found [TestString]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at LearningTestNG.Listeners.LoginTest.loginWithFacebook(LoginTest.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithFacebook -->
      </class> <!-- LearningTestNG.Listeners.LoginTest -->
      <class name="ParallelExecution.TestWebsite">
        <test-method status="FAIL" signature="beforemethod()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="beforemethod" is-config="true" duration-ms="1" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at ParallelExecution.BaseClass.beforemethod(BaseClass.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="SKIP" signature="beforemethod()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="beforemethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="SKIP" signature="test_01()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="test_01" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at ParallelExecution.BaseClass.beforemethod(BaseClass.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_01 -->
        <test-method status="SKIP" signature="aftermethod()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="aftermethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="SKIP" signature="test_02()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="test_02" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at ParallelExecution.BaseClass.beforemethod(BaseClass.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_02 -->
        <test-method status="SKIP" signature="aftermethod()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="aftermethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="SKIP" signature="test_03()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="test_03" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at ParallelExecution.BaseClass.beforemethod(BaseClass.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_03 -->
        <test-method status="SKIP" signature="beforemethod()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="beforemethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="SKIP" signature="aftermethod()[pri:0, instance:ParallelExecution.TestWebsite@42d3bd8b]" name="aftermethod" is-config="true" duration-ms="0" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
      </class> <!-- ParallelExecution.TestWebsite -->
      <class name="SauceLabs.BasicSauceLabTest">
        <test-method status="FAIL" signature="test()[pri:0, instance:SauceLabs.BasicSauceLabTest@26ba2a48]" name="test" duration-ms="53" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[For input string: "518f756cf-114f-40a7-88dc-7871e27"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: For input string: "518f756cf-114f-40a7-88dc-7871e27"
at java.net.URL.<init>(URL.java:627)
at java.net.URL.<init>(URL.java:490)
at java.net.URL.<init>(URL.java:439)
at SauceLabs.BasicSauceLabTest.test(BasicSauceLabTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.NumberFormatException: For input string: "518f756cf-114f-40a7-88dc-7871e27"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.parseInt(Integer.java:615)
at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
at java.net.URL.<init>(URL.java:622)
... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- SauceLabs.BasicSauceLabTest -->
      <class name="LearningTestNG.ReportingTests">
        <test-method status="PASS" signature="login()[pri:0, instance:LearningTestNG.ReportingTests@38082d64]" name="login" duration-ms="1" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="logout()[pri:0, instance:LearningTestNG.ReportingTests@38082d64]" name="logout" duration-ms="1" started-at="2020-02-20T15:53:43Z" finished-at="2020-02-20T15:53:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Test1] but found [Test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Test1] but found [Test]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at LearningTestNG.ReportingTests.logout(ReportingTests.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- LearningTestNG.ReportingTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
